Repository env0/vscode-env0, pull requests merged in 2022-10, with the labels that each got.

#14 readme
  README.md
Labels: documentation, pending final review

#30 Chore: Add MPL 2.0 license
  LICENSE
Labels: pending final review

#29 Feat: add ESLint and Prettier
  .eslintrc.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/actions.ts
  src/env0-environments-provider.ts
  src/extension.ts
  src/get-environments.ts
  src/mock-environments.json
  src/notification-messages.ts
  tsconfig.json
Labels: reviewed - await author
